version: '3'

services:
  zookeeper:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    restart: unless-stopped
    hostname: kafka1
    ports:
      - '9091:9091'
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'kafka-topics.sh --bootstrap-server 127.0.0.1:9091 --topic __consumer_offsets --describe',
        ]
      interval: 2s
      timeout: 2s
      retries: 15

  db-users:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "f@myH*q@DvM9%i" # TODO o correto seria usar uma variavel de ambiente, para facilitar implantacao deixarei dessa maneira
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data_users:/var/opt/mssql

  db-operations:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "f@myH*q@DvM9%i" # TODO o correto seria usar uma variavel de ambiente, para facilitar implantacao deixarei dessa maneira
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - db_data_operations:/var/opt/mssql

volumes:
  db_data_users:
  db_data_operations:
